# -*- coding: utf-8 -*-
"""Projeto PUC - Análise de dados meteorológicos

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wBgbVbYiADrnS9DoXvYBao-Ar1fXegJl

# Análise de Dados Meteorológicos
Este programa visa validar e analisar dados meteorológicos de uma cidade ao longo do ano de um ano. O usuário insere a temperatura máxima registrada para cada mês, e o programa realiza cálculos e análises com base nesses dados.

# Função: `obter_mes_extenso`
Essa função que recebe o número de um mês (1 a 12) e retorna o nome do mês por extenso. Ela é usada para exibir os meses de forma mais amigável ao usuário.
"""

def obter_mes_extenso(mes):
    # Lista com os nomes dos meses
    meses = ["janeiro", "fevereiro", "março", "abril", "maio", "junho",
             "julho", "agosto", "setembro", "outubro", "novembro", "dezembro"]
    # Retorna o nome do mês correspondente ao número fornecido
    return meses[mes - 1]

"""## Funções: `validar_mes` e `validar_temperatura`
Essas funções validam as entradas de usuário. A primeira garantindo que o mês esteja entre 1 e 12, e a segunda garante que a temperatura esteja dentro do intervalo permitido (-60°C a 50°C).

"""

def validar_mes(mes):
    # Verifica se o mês está no intervalo de 1 a 12
    return 1 <= mes <= 12

def validar_temperatura(temp):
    # Verifica se a temperatura está no intervalo de -60°C a 50°C
    return -60 <= temp <= 50

"""## Função: `coletar_dados_ano`
Essa função vai coletar as temperaturas máximas para todos os meses do ano, garantindo que os valores inseridos sejam válidos.

"""

def coletar_dados_ano():
    temperaturas_maximas = []
    for i in range(1, 13):
        while True:
            try:
                mes = i
                if not validar_mes(mes):
                    raise ValueError("Mês inválido. Deve ser um número entre 1 e 12.")

                temp_max = float(input(f"Informe a temperatura máxima registrada no mês de {obter_mes_extenso(mes)}: "))
                if not validar_temperatura(temp_max):
                    raise ValueError("Temperatura inválida. Deve estar entre -60°C e 50°C.")

                # Armazena a temperatura válida
                temperaturas_maximas.append(temp_max)
                break
            except ValueError as e:
                print(e)

    return temperaturas_maximas

"""## Função: `editar_dados`
Esta função permite editar a temperatura máxima de um mês específico, caso o usuário tenha cometido algum erro na entrada dos dados.

"""

def editar_dados(temperaturas_maximas):
    while True:
        try:
            # Solicita o mês a ser editado
            mes_editar = int(input("Digite o número do mês que deseja editar (1-12), ou 0 para sair: "))
            if mes_editar == 0:
                break
            if not validar_mes(mes_editar):
                raise ValueError("Mês inválido. Deve ser um número entre 1 e 12.")

            nova_temp = float(input(f"Informe a nova temperatura máxima para {obter_mes_extenso(mes_editar)}: "))
            if not validar_temperatura(nova_temp):
                raise ValueError("Temperatura inválida. Deve estar entre -60°C e 50°C.")

            # Atualiza a temperatura do mês
            temperaturas_maximas[mes_editar - 1] = nova_temp
            print(f"Temperatura do mês de {obter_mes_extenso(mes_editar)} atualizada para {nova_temp}°C.\n")
        except ValueError as e:
            print(e)

"""## Função: `analisar_dados`
Esta função calcula a média das temperaturas máximas anuais, identifica os meses escaldantes, e encontra o mês mais escaldante e o menos quente do ano.

"""

def analisar_dados(temperaturas_maximas):
    temp_media_anual = sum(temperaturas_maximas) / len(temperaturas_maximas)
    meses_escaldantes = sum(1 for temp in temperaturas_maximas if temp > 33)
    mes_mais_escaldante = temperaturas_maximas.index(max(temperaturas_maximas)) + 1
    mes_menos_quente = temperaturas_maximas.index(min(temperaturas_maximas)) + 1

    print(f"\nTemperatura média máxima anual: {temp_media_anual:.2f}°C")
    print(f"Quantidade de meses escaldantes: {meses_escaldantes}")
    print(f"Mês mais escaldante do ano: {obter_mes_extenso(mes_mais_escaldante)} ({max(temperaturas_maximas)}°C)")
    print(f"Mês menos quente do ano: {obter_mes_extenso(mes_menos_quente)} ({min(temperaturas_maximas)}°C)")

"""## Função Principal: `main`
A função `main` executa todo o fluxo do programa, incluindo coleta, edição, análise dos dados e interação com o usuário.

"""

def main():
    while True:
        print("\nInsira os dados meteorológicos para um novo ano.")
        temperaturas_maximas = coletar_dados_ano()

        while True:
            print("\nEscolha uma opção:")
            print("1. Analisar dados")
            print("2. Editar temperatura de um mês")
            print("3. Inserir dados para outro ano")
            print("4. Sair")

            opcao = input("Opção: ").strip()

            if opcao == '1':
                analisar_dados(temperaturas_maximas)
            elif opcao == '2':
                editar_dados(temperaturas_maximas)
            elif opcao == '3':
                break
            elif opcao == '4':
                print("Saindo...")
                return
            else:
                print("Opção inválida. Tente novamente.")

if __name__ == "__main__":
    main()